### ISSUE TITLE
Update rate of 0

### ISSUE THREAD

**Issue by axkoenig** [jsbruglie/grasp#13]
Thanks for open sourcing this! I have a question regarding your world files. You set ```real_time_update_rate``` to 0 in this line of some of the [world files](https://github.com/jsbruglie/grasp/blob/dev/worlds/empty.world). 

`<real_time_update_rate>0.000000</real_time_update_rate>`

How does an update rate of 0 make sense? Could you explain why you do this?

**Comment by joao-borrego** [comment]
Hi @axkoenig! Glad this repo is still useful from time to time. It's been quite some time but I remembered this detail.
It's a documented feature to uncap the simulation speed: http://gazebosim.org/tutorials?tut=physics_params&cat=physics

> If real_time_update_rate is set to 0 the simulation will run as fast as it can. If Gazebo is not able to update at the desired rate, it will update as fast as it can, based on the computing power.

**Comment by axkoenig** [comment]
Thanks, that makes sense!
