### ISSUE TITLE
libsdformat6-dev, Gazebo dependency lib, not available in Ubuntu 16.04

### ISSUE THREAD

**Issue by aprath1** [jsbruglie/grasp#14]
Wit apt and apt-get I get the following output for the 'libsdformat6-dev' dependency of Gazebo in Ubuntu 16.04:
```
sudo apt install libsdformat6-dev
# output
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libsdformat6-dev
```
Could any one please let me know if this library dependency is correct or am I missing something?

Update:
Only 'libsdformat4-dev' seem to be available in the apt-cache, will this be compatible?

**Comment by aprath1** [comment]
Seems like the apt need to be updated with the osrfoundation gazebo packages. A simple change in order of the installation will resolve the issue:
Referring to [dpendencies](https://github.com/jsbruglie/grasp/blob/dev/.doc/install.md)
First - # Setup OSRF keys
Then - # SDF library

**Comment by joao-borrego** [comment]
First of all thank you for your interest in this repo! It's been ages since I've written the installation procedure.
Since you're taking the time to try running it, if you could update the guide with corrections or suggestions I'd be more than happy to merge them back into the default branch!
